(()=>{try{
if(window.__BIM_V2)return;window.__BIM_V2=1;
const logo='__BIM_LOGO__',q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],red='#CD141A',dark='#3C3735';
const css=document.createElement('style');css.textContent=`:root{--red:${red}!important;--red-dark:#A70F14!important;--text:${dark}!important}.brand-mark,.mini-mark{background:#fff!important;color:transparent!important;background-image:url('${logo}')!important;background-position:center!important;background-repeat:no-repeat!important;background-size:82%!important;border:1px solid #eee!important}.mobile-nav{padding-bottom:max(10px,env(safe-area-inset-bottom))!important;min-height:68px!important;box-shadow:0 -5px 18px #0000000d!important}.mobile-nav button{min-height:48px!important;font-size:11px!important}.btn-primary{background:${red}!important}.card{border-radius:18px!important}.bim-v2-note{font-size:12px;color:#777;margin-top:7px}.bim-v2-status{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:8px 0 14px}.bim-v2-pill{font-size:11px;padding:5px 9px;border-radius:999px;background:#f1f3f5;color:#555}.bim-v2-filter{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.bim-v2-filter input,.bim-v2-filter select{border:1px solid #ddd;border-radius:10px;padding:9px 10px;background:#fff}.bim-v2-modal{position:fixed;inset:0;z-index:99999;background:#0007;display:flex;align-items:center;justify-content:center;padding:20px}.bim-v2-box{width:min(420px,100%);background:#fff;border-radius:20px;padding:22px;box-shadow:0 18px 70px #0004}.bim-v2-box h3{margin:0 0 8px;color:${dark}}.bim-v2-box p{color:#666;line-height:1.7}.bim-v2-actions{display:flex;gap:8px;margin-top:18px}.bim-v2-actions button{flex:1;border:0;border-radius:12px;padding:12px;font-weight:800}.bim-v2-attach{background:${red};color:#fff}.bim-v2-skip{background:#f1f3f5;color:${dark}}.bim-noattach{background:#fff3cd;color:#765b00;border-radius:999px;padding:3px 7px;font-size:10px}`;document.head.appendChild(css);
const stamp=()=>{let e=q('#bimV2Stamp');if(!e){e=document.createElement('div');e.id='bimV2Stamp';e.className='bim-v2-status';const dash=q('#page-dashboard');if(dash)dash.insertBefore(e,dash.children[1]||null)}const role=(typeof state!=='undefined'&&state.user)?state.user.role:'';e.innerHTML=`<span class="bim-v2-pill">آخر تحديث: ${new Date().toLocaleTimeString('ar-SY')}</span><span class="bim-v2-pill">تحديث تلقائي كل 15 ثانية</span>`};
const file=q('#invoiceFile');if(file&&!q('#bimInvoiceNote')){const n=document.createElement('div');n.id='bimInvoiceNote';n.className='bim-v2-note';n.textContent='صورة الفاتورة اختيارية. إذا لم تُرفق صورة سنذكّرك قبل الحفظ، ويمكنك المتابعة بدونها.';file.parentElement.appendChild(n)}
let bypass=false;const form=q('#invoiceForm');if(form)form.addEventListener('submit',e=>{if(bypass){bypass=false;return}const f=q('#invoiceFile');const has=(f&&f.files&&f.files.length)||(typeof state!=='undefined'&&state.selectedFile);if(has)return;e.preventDefault();e.stopImmediatePropagation();const m=document.createElement('div');m.className='bim-v2-modal';m.innerHTML=`<div class="bim-v2-box"><h3>لم تُرفق صورة فاتورة</h3><p>لم يتم إدخال صورة لهذه العملية. إذا كانت الفاتورة موجودة يمكنك إرفاقها الآن، وإذا لم توجد فاتورة يمكنك حفظ العملية بدون مرفق.</p><div class="bim-v2-actions"><button class="bim-v2-attach">إرفاق فاتورة</button><button class="bim-v2-skip">حفظ بدون فاتورة</button></div></div>`;document.body.appendChild(m);m.querySelector('.bim-v2-attach').onclick=()=>{m.remove();f&&f.click()};m.querySelector('.bim-v2-skip').onclick=()=>{m.remove();bypass=true;form.requestSubmit()};},true);
const draftIds=['supplier','requester','currency','invoiceAmount','invoiceNotes'];draftIds.forEach(id=>{const e=q('#'+id);if(!e)return;const k='bimPurchaseDraft_'+id;const v=localStorage.getItem(k);if(v&&!e.value)e.value=v;e.addEventListener('input',()=>localStorage.setItem(k,e.value))});if(form)form.addEventListener('reset',()=>setTimeout(()=>draftIds.forEach(id=>localStorage.removeItem('bimPurchaseDraft_'+id)),0));
let allRows=[];if(typeof renderInvoices==='function'){const original=renderInvoices;window.__bimOriginalRenderInvoices=original;renderInvoices=function(rows){allRows=rows||[];original(filterRows(allRows));ensureFilter()}}
function filterRows(rows){const s=(q('#bimInvSearch')?.value||'').trim().toLowerCase(),f=q('#bimInvAttach')?.value||'all';return rows.filter(r=>{const text=Object.values(r||{}).join(' ').toLowerCase();const has=!!(r.imageUrl||r.image||r.fileUrl||r.attachmentUrl);return(!s||text.includes(s))&&(f==='all'||(f==='with'&&has)||(f==='without'&&!has))})}
function ensureFilter(){if(q('#bimInvFilter'))return;const table=q('#recentInvoices');if(!table)return;const d=document.createElement('div');d.id='bimInvFilter';d.className='bim-v2-filter';d.innerHTML='<input id="bimInvSearch" placeholder="بحث في فواتير اليوم"><select id="bimInvAttach"><option value="all">كل الفواتير</option><option value="with">مع مرفق</option><option value="without">بدون مرفق</option></select>';table.parentElement.insertBefore(d,table);['input','change'].forEach(ev=>d.addEventListener(ev,()=>window.__bimOriginalRenderInvoices&&window.__bimOriginalRenderInvoices(filterRows(allRows))))}
window.__bimV2Refresh=async()=>{try{if(typeof state==='undefined'||!state.token||typeof gs!=='function')return;const p=qa('.page:not(.hidden)')[0]?.id||'';if(!/dashboard|archive/.test(p))return;if(p.includes('archive')){typeof loadArchive==='function'&&loadArchive();return}const res=await gs('refreshDashboard',state.token);state.data=res.data||res;if(res.user)state.user=res.user;typeof render==='function'&&render();stamp()}catch(_){}};
stamp();setTimeout(()=>{if(typeof state!=='undefined'&&state.data&&typeof renderInvoices==='function')renderInvoices(state.data.invoices||[])},200);setInterval(()=>window.__bimV2Refresh(),15000);window.addEventListener('focus',()=>setTimeout(()=>window.__bimV2Refresh(),200));document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(()=>window.__bimV2Refresh(),200)});
}catch(e){console.error('BIM V2',e)}})();